name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag hello-world:$(date +%s)
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build Base Docker image
      run: docker build -f Dockerfile.base -t ghcr.io/${{ github.repository }}/debian-desktop-base:latest .
    - name: Push Base Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}/debian-desktop-base:latest
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}/debian-desktop-docker:latest .
    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}/debian-desktop-docker:latest
